### ISSUE TITLE
add wax

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#200]
http://marii.info/projects/wax/ - minimal IIIF exhibitions with Jekyll.

**Comment by jronallo** [comment]
:+1: This is a quality resource.

**Comment by regisrob** [comment]
re +1! This is an easy to use but powerful tool (just requires some basic knowledge of Jekyll). The documentation is concise and really effective. It did not take me long to understand how it works and see how I can modify it to fit my own needs. For instance I have just started tweaking Wax in order to support IIIF resources that already exist externally. The use case is: I have put together a list of images that I know some of them are IIIF-compliant, and for these images I do not need/want to generate what the wax:iiif task does, but simply use the IIIF endpoints (which of course avoids the need to download every image that is part of the exhibition and recreate IIIF resources that already exist out there).

**Comment by julsraemy** [comment]
+1
