### ISSUE TITLE
scta.lombardpress.com

### ISSUE THREAD

**Issue by jeffreycwitt** [IIIF/awesome-iiif#48]
Can we add this site as an implementor of IIIF: 

http://scta.lombardpress.org

Code base is here: http://github.com/lombardpress/lombardpress-web

The client viewer displays TEI encoded editions of texts (critical and diplomatic) and allows users to view the facsimiles behind those transcriptions via requests to images on IIIF compliant servers throughout the world. 

Thanks

**Comment by jronallo** [comment]
@jeffreycwitt We've recently discussed constraining the scope some of what goes on the list. We are likely going to look to capture adopters and information about their implementation(s) some other way so as not to overwhelm this list. I'm going to leave this open for now as we finalize a decision and so that we can let you know when we'd be accepting submissions for that list of adopters.

**Comment by jeffreycwitt** [comment]
@jronallo ok, sounds great :)

**Comment by jeffreycwitt** [comment]
Any update on this. Can I submit a pull request to have this added under "implementations"?

**Comment by julsraemy** [comment]
What shall we do with this issue regarding #133 (as the SCTA is now on the the Mirador Awesome Repo). Shall we still put it under Implementations?

**Comment by jronallo** [comment]
@jeffreycwitt Sorry it took so long to resolve this issue!
